### ISSUE TITLE
Grant's in the readme are not up to date

### ISSUE THREAD

**Issue by MBloom** [llooker/blocks_redshift_admin#13]
The tables which you need to grant privileges for are not up to date with the most recent views.

**Comment by fabio-looker** [comment]
Are there specific tables which you noticed you did not already have select permissions for?

**Comment by MBloom** [comment]
I have noticed is that the standard user I created was unable to read some data from `pg_catalog.stl_load_commits` (as used in the [redshift_data_loads](https://github.com/llooker/blocks_redshift_admin/blob/master/redshift_views.view.lkml#L113) view).

I came across [this page](http://docs.aws.amazon.com/redshift/latest/dg/c_visibility-of-data.html) from AWS that mentions the following:

> There are two classes of visibility for data in system tables and views: user visible and visible to superusers. Only users with superuser privileges can see the data in those tables that are in the superuser visible category. Regular users can see data in the user visible tables. In most cases, rows generated by another user are invisible to a regular user.

Now I'm not sure if `stl_load_commits` is a user visible, table but it would be nice to use this block to monitor our performance with FiveTran as well as Looker. This leads me to believe that we would need to create a superuser connection, as opposed to using the recommended standard connection.

**Comment by fabio-looker** [comment]
Yes, you could either set up a super-user connection to report across both users, or you could simply set up a second model that connects as this other user. In any case, if you did go the super-user route, you would want to be careful about who you allow to access that model, as noted in the installation section

**Comment by fabio-looker** [comment]
Documentation updated with this permission. Thanks!
