### ISSUE TITLE
Custom viz - Flame graph for query plan

### ISSUE THREAD

**Issue by fabio-looker** [llooker/blocks_redshift_admin#34]
To replace the hard-to-use table in the Redshift Query Inspection dashboard

https://blog.tanelpoder.com/posts/visualizing-sql-plan-execution-time-with-flamegraphs/

**Comment by fabio-looker** [comment]
@davidtamaki - FYI, this was the FR ticket I had made for this a while back.

We should probably include the viz code in the block itself :)

**Comment by davidtamaki** [comment]
Here's the flamegraph-looker repo with examples & instructions: https://github.com/davidtamaki/flamegraph

Commits to the block:
- modifying redshift_plan_steps PDT to add incremental step costs: https://github.com/fabio-looker/blocks_redshift_admin/commit/75052f95fcf3bbc0e973007f7b5bf6aa993c7b02
flamegraph.js
- adding flamegraph.js for query plan: https://github.com/fabio-looker/blocks_redshift_admin/commit/b337e6a8c351ccb3a04f5c72b35caea5384877aa
- adding deployment instructions: https://github.com/fabio-looker/blocks_redshift_admin/commit/56061b05c507ae0bbbac78e1e60810697d768d24

**Comment by davidtamaki** [comment]
Updating dashboard with vis: https://github.com/fabio-looker/blocks_redshift_admin/commit/147b03ce676c084686f87fe68cf3e5996562a380
