### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by buremba** [llooker/blocks_redshift_admin#37]
Could you please add a license to the project? In fact, most of the repos under this account don't have any license so I'm not sure if we can use it on our own* or in Looker. 

*: Parsing the LookML and using it for something else.

**Comment by DillonMorrison** [comment]
@buremba all Blocks that Looker distributed through our repositories are licensed under MIT license.  You're free and encouraged to use this in your own Looker. Thanks for calling this out

**Comment by buremba** [comment]
Thanks for the clarification. Is there a publicly available license for LookML?

**Comment by fabio-looker** [comment]
Hi @buremba - as a language, I'm not sure whether LookML is a copyrightable/licensable thing. That said, I have made a LookML parser and grammar that are published under an MIT license here: 
https://github.com/fabio-looker/node-lookml-parser

This seems resolved, but don't hesitate to add more comments if needed.

**Comment by DillonMorrison** [comment]
@buremba to clarify, LookML as a concept is not something we can license out to anyone. The specific LookML for this Block is under MIT license.
