### ISSUE TITLE
redshift_tables view in block is broken, due to Invalid character data in sortkey1 column of svv_table_info table

### ISSUE THREAD

**Issue by molly-looker** [llooker/blocks_redshift_admin#38]
PDT in this view is failing: 
view: redshift_tables {
  derived_table: {
    # Insert into PDT because redshift won't allow joining certain system tables/views onto others (presumably because they are located only on the leader node)
    persist_for: "8 hours"
    sql: select
        "database"::varchar,
        "schema"::varchar,
        "Table_id"::bigint,
        "table"::varchar,
        "encoded"::varchar,
        "diststyle"::varchar,
        "sortkey1"::varchar,
        "max_varchar"::bigint,
        "sortkey1_enc"::varchar,
        "sortkey_num"::int,
        "size"::bigint,
        "pct_used"::numeric,
        "unsorted"::numeric,
        "stats_off"::numeric,
        "tbl_rows"::bigint,
        "skew_sortkey1"::numeric,
        "skew_rows"::numeric
      from svv_table_info
    ;;
    # http://docs.aws.amazon.com/redshift/latest/dg/r_SVV_TABLE_INFO.html
      distribution_style: all
      indexes: ["table_id","table"] # "indexes" translates to an interleaved sort key for Redshift
    }

This is due to the "sortkey1" column, we see the error when we select just that column: 
select "sortkey1"::varchar from svv_table_info
====>
The Amazon Redshift database encountered an error while running this query.
Invalid character data was found. This is most likely caused by stored data containing characters that are invalid for the character set the database was created in. The most common example of this is storing 8bit data in a SQL_ASCII database.

**Comment by fabio-looker** [comment]
@molly-looker  Neither Looking at Redshift docs nor 15 minutes of searching turned up a reliable answer that addresses this. If they are willing to test, could you ask them if something like `SELECT REGEXP_REPLACE("sortkey1", '[^ -~]', '?')::varchar from svv_table_info` still errors?

**Comment by fabio-looker** [comment]
Handled by https://github.com/llooker/blocks_redshift_admin/commit/1a3ff8e2dfa5c00fb22c184801126fa5ab56a9b2
