### ISSUE TITLE
Redact/scrub string values by default in transformed query text/plan tables

### ISSUE THREAD

**Issue by fabio-looker** [llooker/blocks_redshift_admin#39]
Since strings may contain sensitive data, e.g. within filter values, it would be good to use a regex to redact all strings by default when creating the block's PDTs

**Comment by taylor67** [comment]
+1 Avalere health

**Comment by taylor67** [comment]
### Places to update:

Table: [redshift_queries](https://github.com/llooker/blocks_redshift_admin/blob/master/redshift_views.view.lkml#L396)
- Columns: text, snippet
 - Come from Redshift system tables: 
    - SVL_QLOG.substring - Truncated query text (from redshift docs)
    - STL_QUERY.querytxt - Actual query text for the query

Table: [redshift_plan_steps](https://github.com/llooker/blocks_redshift_admin/blob/master/redshift_views.view.lkml#L183)
 - Column: operation_argument
 - Come from Redshift system tables: 
    - stl_explain.plannode - The node text from the EXPLAIN output

**Comment by fabio-looker** [comment]
Resolved by the above PR
